flaskapp_boy_or_girl/main/routes.py
from flask import render_template, request, redirect, Blueprint, current_app, url_for
from flaskapp_boy_or_girl.main.utils import get_BG_table, html_table_with_intersection
from datetime import date, datetime, timedelta

from flaskapp_boy_or_girl.main.forms import InfoForm, PlanbyGender, PlanbyDate
import pandas as pd

import os
from bs4 import BeautifulSoup

main  = Blueprint('main', __name__)

@main.route("/", methods=['GET', 'POST'])
@main.route("/home", methods=['GET', 'POST'])
def check():
	form = InfoForm()

	pulled_table = get_BG_table()
	df_table = pulled_table.reset_index(inplace=False).rename({'Month':''}, axis=1).to_html(classes=['table', 'table-bordered', 'table-sm', 'text-center'], index=False)

	if form.validate_on_submit() and request.method == 'POST':

		days_in_womb = form.days_in_womb.data
		mother_birthday = form.mother_birthday.data
		my_birthday = form.my_birthday.data
		today = date.today()

		concieve_date = (my_birthday - timedelta(days=days_in_womb))
		mother_age_whenconcieved = concieve_date.year - mother_birthday.year - ((concieve_date.month, concieve_date.day) < (mother_birthday.month, mother_birthday.day))
		concieve_month = concieve_date.strftime("%b")
		my_age = today.year - my_birthday.year - ((today.month, today.day) < (my_birthday.month, my_birthday.day))
		my_age = my_age if my_age >= 0 else 0

		bg_color = 'bg-danger'
		text_color = 'text-white'

		if my_birthday == mother_birthday:
			error_msg = 'The child and the mother were born at the same time???'
			return render_template('lets_check.html', error_msg=error_msg, bg_color=bg_color, text_color=text_color, df_table=df_table, form=form)
		elif my_birthday < mother_birthday:
			error_msg = 'The Child was born before the mother???'
			return render_template('lets_check.html', error_msg=error_msg, bg_color=bg_color, text_color=text_color, df_table=df_table, form=form)
		elif mother_age_whenconcieved < 18 or mother_age_whenconcieved > 45:
			error_msg = 'The Mother\'s age can only be between 18 and 45 years during the conception.'
			return render_template('lets_check.html', error_msg=error_msg, bg_color=bg_color, text_color=text_color, df_table=df_table, form=form)
		elif days_in_womb not in range(1,366):
			error_msg = 'Pregnancy duration can only be between 1 and 365 days.'
			return render_template('lets_check.html', error_msg=error_msg, bg_color=bg_color, text_color=text_color, df_table=df_table, form=form)


		

		result = pulled_table[mother_age_whenconcieved].loc[concieve_month]
		result = 'Boy' if result=='B' else "Girl"
		df_table = html_table_with_intersection(html_table=df_table, month_conception=concieve_month, mom_age_at_conception=mother_age_whenconcieved, sex=result)
		bg_color = 'bg-primary' if result=='Boy' else 'bg-pink'
		text_color = 'text-white'

		details = {'mother_age_whenconcieved': mother_age_whenconcieved,
				   'concieve_date': concieve_date.strftime("%b %d, %Y"),
				   'concieve_month': concieve_date.strftime("%B"),
				   'my_age': my_age}

		return render_template('lets_check.html', result=result, bg_color=bg_color, text_color=text_color, details=details, df_table=df_table, form=form)


	else:
		welcome_msg = 'Please fill out the form'
		bg_color = 'bg-light'
		text_color = 'text-black'


	return render_template('lets_check.html', welcome_msg=welcome_msg, bg_color=bg_color, text_color=text_color, df_table=df_table, form=form)
	




@main.route("/gender", methods=['GET', 'POST'])
def plan_by_gender():
	form = PlanbyGender()

	pulled_table = get_BG_table()
	df_table = pulled_table.reset_index(inplace=False).rename({'Month':''}, axis=1).to_html(classes=['table', 'table-bordered', 'table-sm', 'text-center'], index=False)

	mother_max_age = 45
	show_max_potential_months = 3

	if form.validate_on_submit() and request.method == 'POST':

		mother_birthday = form.mother_birthday.data
		gender = 'B' if form.gender.data=='Boy' else 'G'
		today = date.today()
		current_month = date.today().month # [1-12]
		month_mapping = {'Jan':1, 'Feb':2, 'Mar':3, 'Apr':4, 'May':5, 'Jun':6, 'Jul':7, 'Aug':8, 'Sep':9, 'Oct':10, 'Nov':11, 'Dec':12}

		mother_age = today.year - mother_birthday.year - ((today.month, today.day) < (mother_birthday.month, mother_birthday.day))


		bg_color = 'bg-danger'
		text_color = 'text-white'

		if mother_age < 18 or mother_age > 45:
			error_msg = 'The Mother\'s age can only be between 18 and 45 years during the conception.'
			return render_template('plan_by_gender.html', error_msg=error_msg, bg_color=bg_color, text_color=text_color, df_table=df_table, mother_age=mother_age, form=form)

		df_current = pulled_table[pulled_table[mother_age]==gender][mother_age]
		df_current_goodMonths = df_current[df_current.index.map(month_mapping) >= current_month].index
		df_current = pd.DataFrame({'month_idx':df_current_goodMonths.map(month_mapping),\
								   'month':df_current_goodMonths,
								   'year':today.year})

		df_future_goodMonths = []
		if mother_age < mother_max_age:
			df_future_goodMonths = pulled_table[pulled_table[mother_age+1]==gender][mother_age+1].index
			df_current = df_current.append(pd.DataFrame({'month_idx':df_future_goodMonths.map(month_mapping),\
												   		 'month':df_future_goodMonths,
												   		 'year':today.year + 1}))


		bg_color = 'bg-primary' if form.gender.data=='Boy' else 'bg-pink'
		text_color = 'text-white'

		result = True if not df_current.empty else False
		info_message = 'Plan to concieve in:' if not df_current.empty else 'Sorry. We couldn\'t the potential months based on the data you provided.'
		details = {'potential_months':df_current.head(show_max_potential_months),\
				   'info_message':info_message,
				   'anticipated_gender':form.gender.data}


		return render_template('plan_by_gender.html',\
								form=form,\
								df_table=df_table,\
								result=result,\
								details=details,\
								mother_age=mother_age,
								bg_color=bg_color,\
								text_color=text_color)

	else:
		welcome_msg = 'Please fill out the form'
		bg_color = 'bg-light'
		text_color = 'text-black'

				

	return render_template('plan_by_gender.html',\
							form=form,\
							df_table=df_table,\
							welcome_msg=welcome_msg,\
							bg_color=bg_color,\
							text_color=text_color)


@main.route("/date", methods=['GET', 'POST'])
def plan_by_date():
	form = PlanbyDate()

	pulled_table = get_BG_table()
	df_table = pulled_table.reset_index(inplace=False).rename({'Month':''}, axis=1).to_html(classes=['table', 'table-bordered', 'table-sm', 'text-center'], index=False)

	if form.validate_on_submit() and request.method == 'POST':


		mother_birthday = form.mother_birthday.data
		concieve_date = form.conception_date.data
		days_in_womb = form.days_in_womb.data
		concieve_month = concieve_date.strftime("%b")
		mother_age_whenconcieved = concieve_date.year - mother_birthday.year - ((concieve_date.month, concieve_date.day) < (mother_birthday.month, mother_birthday.day))

		bg_color = 'bg-danger'
		text_color = 'text-white'

		if concieve_date <= mother_birthday:
			error_msg = 'The Conception date has to be after the mother\'s date of birth.'
			return render_template('plan_by_date.html', error_msg=error_msg, bg_color=bg_color, text_color=text_color, df_table=df_table, form=form)
		elif mother_age_whenconcieved < 18 or mother_age_whenconcieved > 45:
			error_msg = 'The Mother\'s age can only be between 18 and 45 years during the conception.'
			return render_template('plan_by_date.html', error_msg=error_msg, bg_color=bg_color, error_mother_age_concieved=mother_age_whenconcieved, text_color=text_color, df_table=df_table, form=form)
		elif days_in_womb not in range(1,366):
			error_msg = 'Pregnancy duration can only be between 1 and 365 days.'
			return render_template('plan_by_date.html', error_msg=error_msg, bg_color=bg_color, text_color=text_color, df_table=df_table, form=form)	


		result = pulled_table[mother_age_whenconcieved].loc[concieve_month]
		result = 'Boy' if result=='B' else "Girl"

		child_birthday = (concieve_date + timedelta(days=days_in_womb))

		df_table = html_table_with_intersection(html_table=df_table, month_conception=concieve_month, mom_age_at_conception=mother_age_whenconcieved, sex=result)
		bg_color = 'bg-primary' if result=='Boy' else 'bg-pink'
		text_color = 'text-white'

		details = {'mother_age_whenconcieved': mother_age_whenconcieved,
				   'concieve_date': concieve_date.strftime("%b %d, %Y"),
				   'child_birthday': child_birthday.strftime("%b %d, %Y")}

		return render_template('plan_by_date.html', result=result, bg_color=bg_color, text_color=text_color, details=details, df_table=df_table, form=form)	   

	else:
		welcome_msg = 'Please fill out the form'
		bg_color = 'bg-light'
		text_color = 'text-black'

				

	return render_template('plan_by_date.html',\
							form=form,\
							df_table=df_table,\
							welcome_msg=welcome_msg,\
							bg_color=bg_color,\
							text_color=text_color)

flaskapp_boy_or_girl/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Boy or Girl</title>

        <style>
	    	.bg-pink{
	    		background: #d63384 !important;
	    	}

	    	.bg-lighbackground{
	    		background: #eadbc8 !important;	
	    	}
    	</style>


  </head>
  <body>
	<div class="container mt-4 mb-4">
		<div class="row">
			<div class="col-lg-12">
				<div class="card">
				  <div class="card-header mb-4">
				    <ul class="nav nav-tabs card-header-tabs">

				      <li class="nav-item">
				      	{% if active_page == "lets_check" %}
				      		<a class="nav-link active" aria-current="true" href="#">Let's check</a>
				      	{% else %}
				      		<a class="nav-link" href="{{ url_for('main.check') }}">Let's check</a>
				      	{% endif %}
				      </li>

				      <li class="nav-item">
				      	{% if active_page == "plan_by_gender" %}
				      		<a class="nav-link active" aria-current="true" href="#">Plan by anticipated gender</a>
				      	{% else %}
				      		<a class="nav-link" href="{{ url_for('main.plan_by_gender') }}">Plan by anticipated gender</a>
				      	{% endif %}
				      </li>

				      <li class="nav-item">
				      	{% if active_page == "plan_by_date" %}
				      		<a class="nav-link active" aria-current="true" href="#">Plan by anticipated conception date</a>
				      	{% else %}
				      		<a class="nav-link" href="{{ url_for('main.plan_by_date') }}">Plan by anticipated conception date</a>
				      	{% endif %}
				      </li>

				    </ul>
				  </div>
				  <div class="card-body">


				  	{% block content %}

				  	{% endblock %}

			  		<!-- start table row -->
					<div class='row'>
						<div class='col-lg-12'>
							<div class="card mt-4">
							  <div class="card-body text-center">
							    <h5 class="card-title">Boy or Girl</h5>
							    <p class="card-text">According to this table, which is created by old chinese disciples, one can guess a child's gender. On a horizontal line - mother's age (in years) 18 - 45. On a vertical line - conception month. </p>

							    		<div class='overflow-auto'>{{ df_table|safe }}</div>
							  </div>
							  <div class="card-footer text-muted text-left">
							  	<small>
							  	Vertical line: conception month<br>
							  	Horzontal line: mother's age (in years) 18 - 45
							  </small>
							  </div>
							</div>
						</div>
					</div>

				  	
				  </div> <!-- end main card body -->

				  <div class="card-footer mt-4 text-center text-muted">
				    <small>Disclaimer: I, Giorgi Kochiashvili, take no responsibility for the accuracy of the table or results displayed by this application.</small>
				  </div>

				</div> <!-- end main card -->
			</div> <!-- end col-12 -->
		</div> <!-- end row -->
	</div> <!-- end container -->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>

flaskapp_boy_or_girl/templates/lets_check.html
{% extends "layout.html" %}

{% set active_page = "lets_check" %}

{% block content %}


	<div class='row'>
		<div class='col-lg-6 mb-4'>
			<div class="card text-center">
			  <h3 class="card-header p-3 text-center">
			    Let's check
			  </h3>
			  <div class="card-body">
				<form method="POST" action="" enctype="multipart/form-data">
					{{ form.hidden_tag() }}

					<fieldset>

						<div class="form-group mt-4">
				            {{ form.mother_birthday.label(class="form-control-label") }}
				            {% if form.mother_birthday.errors %}
				                {{ form.mother_birthday(class="form-control is-invalid") }}
				                <div class="invalid-feedback">
				                    {% for error in form.mother_birthday.errors %}
				                        <span>{{ error }}</span>
				                    {% endfor %}
				                </div>
				            {% else %}
				                {{ form.mother_birthday(class="form-control") }}
				            {% endif %}
			        	</div>

						<div class="form-group mt-4">
				            {{ form.my_birthday.label(class="form-control-label") }}
				            {% if form.my_birthday.errors %}
				                {{ form.my_birthday(class="form-control is-invalid") }}
				                <div class="invalid-feedback">
				                    {% for error in form.my_birthday.errors %}
				                        <span>{{ error }}</span>
				                    {% endfor %}
				                </div>
				            {% else %}
				                {{ form.my_birthday(class="form-control") }}
				            {% endif %}
			        	</div>

						<div class="form-group mt-4">
				            {{ form.days_in_womb.label(class="form-control-label") }}
				            {% if form.days_in_womb.errors %}
				                {{ form.days_in_womb(class="form-control is-invalid") }}
				                <div class="invalid-feedback">
				                    {% for error in form.days_in_womb.errors %}
				                        <span>{{ error }}</span>
				                    {% endfor %}
				                </div>
				            {% else %}
				                {{ form.days_in_womb(class="form-control") }}
				            {% endif %}
			        	</div>	        	

		        	</fieldset>

		        	<div class="form-group mt-4">
		            	{{ form.submit(class="btn btn-lg btn-outline-info") }}
		        	</div>

				</form>
			  </div>

			</div>
		</div>




		<div class='col-lg-6'>
			<div class="card {{bg_color}} {{text_color}}">
			  <h3 class="card-header p-3 text-center">
	          	{% if result%}
	        		It's a {{result}}
	    		{% elif error_msg %}
	    			Error
				{% elif welcome_msg %}
					Welcome
	    		{% endif %}
			  </h3>
			  <div class="card-body">
			  	{% if result%}
			    	<h4 class="card-title">Details:</h4>
			    {% else %}
			    	<h4 class="card-title">Message:</h4>
			    {% endif %}
			    <p class="card-text">
			    	{% if result%}
				    	<ul class="list-group list-group-flush bg-primary">
						  <li class="list-group-item {{bg_color}} {{text_color}} border-white">Mother's age when the child was concieved: {{details['mother_age_whenconcieved']}}</li>
						  <li class="list-group-item {{bg_color}} {{text_color}} border-white">Concieve date: {{details['concieve_date']}}</li>
						  <li class="list-group-item {{bg_color}} {{text_color}} border-white">Concieve month: {{details['concieve_month']}}</li>
						  <li class="list-group-item {{bg_color}} {{text_color}} border-white">The child's age now (in years): {{details['my_age']}}</li>
						</ul>
					{% elif error_msg %}
						<p class="card-text"> {{error_msg}} </p>
					{% elif welcome_msg %}
						<p class="card-text"> {{welcome_msg}} </p>
			    	{% endif %}
			    </p>
			  </div>
			</div>
		</div>
	</div>


{% endblock content %}

flaskapp_boy_or_girl/templates/plan_by_date.html
{% extends "layout.html" %}

{% set active_page = "plan_by_date" %}

{% block content %}


	<div class='row'>
		<div class='col-lg-6 mb-4'>
			<div class="card text-center">
			  <h3 class="card-header p-3 text-center">
			    Plan by Conception Date
			  </h3>
			  <div class="card-body">
				<form method="POST" action="" enctype="multipart/form-data">
					{{ form.hidden_tag() }}

					<fieldset>

						<div class="form-group mt-4">
				            {{ form.mother_birthday.label(class="form-control-label") }}
				            {% if form.mother_birthday.errors %}
				                {{ form.mother_birthday(class="form-control is-invalid") }}
				                <div class="invalid-feedback">
				                    {% for error in form.mother_birthday.errors %}
				                        <span>{{ error }}</span>
				                    {% endfor %}
				                </div>
				            {% else %}
				                {{ form.mother_birthday(class="form-control") }}
				            {% endif %}
			        	</div>

						<div class="form-group mt-4">
				            {{ form.conception_date.label(class="form-control-label") }}
				            {% if form.conception_date.errors %}
				                {{ form.conception_date(class="form-control is-invalid") }}
				                <div class="invalid-feedback">
				                    {% for error in form.conception_date.errors %}
				                        <span>{{ error }}</span>
				                    {% endfor %}
				                </div>
				            {% else %}
				                {{ form.conception_date(class="form-control") }}
				            {% endif %}
			        	</div>

						<div class="form-group mt-4">
				            {{ form.days_in_womb.label(class="form-control-label") }}
				            {% if form.days_in_womb.errors %}
				                {{ form.days_in_womb(class="form-control is-invalid") }}
				                <div class="invalid-feedback">
				                    {% for error in form.days_in_womb.errors %}
				                        <span>{{ error }}</span>
				                    {% endfor %}
				                </div>
				            {% else %}
				                {{ form.days_in_womb(class="form-control") }}
				            {% endif %}
			        	</div>	        	

		        	</fieldset>

		        	<div class="form-group mt-4">
		            	{{ form.submit(class="btn btn-lg btn-outline-info") }}
		        	</div>

				</form>
			  </div>

			</div>
		</div>




		<div class='col-lg-6'>
			<div class="card {{bg_color}} {{text_color}}">
			  <h3 class="card-header p-3 text-center">
	          	{% if result%}
	        		It will be a {{result}}
	    		{% elif error_msg %}
	    			Error
				{% elif welcome_msg %}
					Welcome
	    		{% endif %}
			  </h3>
			  <div class="card-body">
			  	{% if result%}
			    	<h4 class="card-title">Details:</h4>
			    {% else %}
			    	<h4 class="card-title">Message:</h4>
			    {% endif %}
			    <p class="card-text">
			    	{% if result%}
				    	<ul class="list-group list-group-flush bg-primary">
						  <li class="list-group-item {{bg_color}} {{text_color}} border-white">Mother's age when the child will be concieved: {{details['mother_age_whenconcieved']}}</li>
						  <li class="list-group-item {{bg_color}} {{text_color}} border-white">Conception date: {{details['concieve_date']}}</li>
						  <li class="list-group-item {{bg_color}} {{text_color}} border-white">The child will be born on: {{details['child_birthday']}}</li>
						</ul>
					{% elif error_msg %}
						<p class="card-text"> {{error_msg}} </p>
					{% elif welcome_msg %}
						<p class="card-text"> {{welcome_msg}} </p>
			    	{% endif %}
			    </p>
			  </div>
		  	  {% if error_mother_age_concieved %}
				  <div class="card-footer">
				    Mother's age during conception (in years): {{ error_mother_age_concieved }}
				  </div>
			  {% endif %}

			</div>
		</div>
	</div>


{% endblock content %}

flaskapp_boy_or_girl/templates/plan_by_gender.html
{% extends "layout.html" %}

{% set active_page = "plan_by_gender" %}

{% block content %}


	<div class='row'>
		<div class='col-lg-6 mb-4'>
			<div class="card text-center">
			  <h3 class="card-header p-3 text-center">
			    Plan by Anticipated Gender
			  </h3>
			  <div class="card-body">
				<form method="POST" action="" enctype="multipart/form-data">
					{{ form.hidden_tag() }}

					<fieldset>

						<div class="form-group mt-4">
				            {{ form.mother_birthday.label(class="form-control-label") }}
				            {% if form.mother_birthday.errors %}
				                {{ form.mother_birthday(class="form-control is-invalid") }}
				                <div class="invalid-feedback">
				                    {% for error in form.mother_birthday.errors %}
				                        <span>{{ error }}</span>
				                    {% endfor %}
				                </div>
				            {% else %}
				                {{ form.mother_birthday(class="form-control") }}
				            {% endif %}
			        	</div>

						<div class="form-group mt-4">
				            {{ form.gender.label(class="form-control-label") }}
				            {% if form.gender.errors %}
				                {{ form.gender(class="form-control form-select is-invalid") }}
				                <div class="invalid-feedback">
				                    {% for error in form.gender.errors %}
				                        <span>{{ error }}</span>
				                    {% endfor %}
				                </div>
				            {% else %}
				                {{ form.gender(class="form-control form-select") }}
				            {% endif %}
			        	</div>

		        	</fieldset>

		        	<div class="form-group mt-4">
		            	{{ form.submit(class="btn btn-lg btn-outline-info") }}
		        	</div>

				</form>
			  </div>

			</div>
		</div>




		<div class='col-lg-6'>
			<div class="card {{bg_color}} {{text_color}}">
			  <h3 class="card-header p-3 text-center">
	          	{% if result%}
	        		To have a {{ details['anticipated_gender'] }}
	    		{% elif error_msg %}
	    			Error
				{% elif welcome_msg %}
					Welcome
	    		{% endif %}
			  </h3>
			  <div class="card-body">

			    {% if not result %}
			    	<h4 class="card-title">Message:</h4>
			    {% endif %}

			    <p class="card-text">
			    	{% if result%}
			    		{{details['info_message']}}
				    	<ul class="list-group list-group-flush bg-primary">
				    	  {% for key,value in details['potential_months'].iterrows() %}
				    	  	<li class="list-group-item {{bg_color}} {{text_color}} border-white">{{ value['month'] }} {{ value['year'] }}</li>
				    	  {% endfor %}
						</ul>

					{% elif error_msg %}
						<p class="card-text"> {{error_msg}} </p>
					{% elif welcome_msg %}
						<p class="card-text"> {{welcome_msg}} </p>
			    	{% endif %}
			    </p>
			  </div>

			  	  {% if mother_age %}
					  <div class="card-footer">
					    Mother's age as of today (in years): {{ mother_age }}
					  </div>
				  {% endif %}


			</div>
		</div>
	</div>


{% endblock content %}